### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SnowMakerDemo** [jython/frozen-mirror#179]
C:\Users\86176>jython -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple synonyms
[33mDEPRECATION: A future version of pip will drop support for Python 2.7.[0m
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting synonyms
[?25l  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3e/47/065b8f34aad7bbf34447df72e4188a5ac6ae7106af5e2f91f5a0ed33f4e0/synonyms-3.10.2.tar.gz (54.5MB)
[K     |████████████████████████████████| 54.5MB 487kB/s eta 0:00:01D:\learn\jython2.7.2\Lib\_io.py:334: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
java.lang.OutOfMemoryError: Java heap space
Jython internals might be in a bad state now that can cause deadlocks later on.
See http://bugs.jython.org/issue2536 for details.
  return bytes(self._buffer)
[33mWARNING: You are using pip version 19.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
Traceback (most recent call last):
  File "D:\learn\jython2.7.2\Lib\runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\learn\jython2.7.2\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\__main__.py", line 19, in <module>
    sys.exit(_main())
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\__init__.py", line 78, in main
    return command.main(cmd_args)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\resolve.py", line 130, in resolve
    discovered_reqs.extend(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\resolve.py", line 130, in resolve
    discovered_reqs.extend(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\resolve.py", line 240, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\operations\prepare.py", line 349, in prepare_linked_requirement
    unpack_url(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\operations\prepare.py", line 349, in prepare_linked_requirement
    unpack_url(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 880, in unpack_url
    unpack_http_url(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 742, in unpack_http_url
    from_path, content_type = _download_http_url(link,
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 954, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\utils\hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 651, in written_chunks
    for chunk in chunks:
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 616, in resp_read
    for chunk in resp.raw.stream(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_internal\download.py", line 616, in resp_read
    for chunk in resp.raw.stream(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 65, in read
    self._close()
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 299, in cache_response
    self.cache.set(
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 72, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\msgpack\__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "D:\learn\jython2.7.2\Lib\site-packages\pip\_vendor\msgpack\fallback.py", line 858, in pack
    ret = self._buffer.getvalue()
  File "D:\learn\jython2.7.2\Lib\_io.py", line 334, in getvalue
    return bytes(self._buffer)
java.lang.OutOfMemoryError: Java heap space
        at org.python.core.BaseBytes.asString(BaseBytes.java:1121)
        at org.python.core.PyByteArray.bytearray_str(PyByteArray.java:2018)
        at org.python.core.PyByteArray.__str__(PyByteArray.java:2013)
        at org.python.core.PyString.str_new(PyString.java:172)
        at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
        at org.python.core.PyType.invokeNew(PyType.java:1119)
        at org.python.core.PyType.type___call__(PyType.java:2399)
        at org.python.core.PyType.__call__(PyType.java:2389)
        at org.python.core.PyObject.__call__(PyObject.java:461)
        at org.python.core.PyObject.__call__(PyObject.java:465)
        at _io$py.getvalue$32(D:/learn/jython2.7.2/Lib/_io.py:334)
        at _io$py.call_function(D:/learn/jython2.7.2/Lib/_io.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:173)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
        at org.python.core.PyFunction.__call__(PyFunction.java:416)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at pip._vendor.msgpack.fallback$py.pack$34(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\msgpack\fallback.py:863)
        at pip._vendor.msgpack.fallback$py.call_function(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\msgpack\fallback.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:173)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
        at org.python.core.PyFunction.__call__(PyFunction.java:426)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at pip._vendor.msgpack$py.packb$4(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\msgpack\__init__.py:47)
        at pip._vendor.msgpack$py.call_function(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\msgpack\__init__.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:173)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
        at org.python.core.PyFunction.function___call__(PyFunction.java:474)
        at org.python.core.PyFunction.__call__(PyFunction.java:469)
        at pip._vendor.cachecontrol.serialize$py.dumps$4(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\cachecontrol\serialize.py:72)
        at pip._vendor.cachecontrol.serialize$py.call_function(C:\Users\86176\AppData\Local\Temp\pip-install-7tzluu\pip\pip\_vendor\cachecontrol\serialize.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:173)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space

**Comment by jeff5** [comment]
That's quite a big chunk it choked on.

You can pass arguments to java with -J (or set them in environment variable JAVA_OPTS), as in -J-Xmx512m to increase heap size.

**Comment by jeff5** [comment]
Assuming the memory options solved this.
