### ISSUE TITLE
pip install failed with HTTP 403 Client Error: SNI is required

### ISSUE THREAD

**Issue by gfiedler** [jython/frozen-mirror#188]
```
# jython --version
Jython 2.7.2
```
```
# jython -m ensurepip
DEPRECATION: A future version of pip will drop support for Python 2.7.
Looking in links: /tmp/tmpBTQpnF
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-19.1 setuptools-41.0.1
```
```
# jython -m pip install -v requests
DEPRECATION: A future version of pip will drop support for Python 2.7.
Created temporary directory: /tmp/pip-ephem-wheel-cache-sBjMKF
Created temporary directory: /tmp/pip-req-tracker-fsqo0e
Created requirements tracker '/tmp/pip-req-tracker-fsqo0e'
Created temporary directory: /tmp/pip-install-0N8O8E
Collecting requests
  1 location(s) to search for versions of requests:
  * https://pypi.org/simple/requests/
  Getting page https://pypi.org/simple/requests/
  Looking up "https://pypi.org/simple/requests/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/requests/ HTTP/1.1" 403 16
  Status code 403 not in (200, 203, 300, 301)
  Could not fetch URL https://pypi.org/simple/requests/: 403 Client Error: SNI is required for url: https://pypi.org/simple/requests/ - skipping
  ERROR: Could not find a version that satisfies the requirement requests (from versions: none)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-fsqo0e'
ERROR: No matching distribution found for requests
Exception information:
Traceback (most recent call last):
  File "/usr/local/Lib/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/Lib/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Lib/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Lib/site-packages/pip/_internal/resolve.py", line 130, in resolve
    discovered_reqs.extend(
  File "/usr/local/Lib/site-packages/pip/_internal/resolve.py", line 130, in resolve
    discovered_reqs.extend(
  File "/usr/local/Lib/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Lib/site-packages/pip/_internal/resolve.py", line 240, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "/usr/local/Lib/site-packages/pip/_internal/operations/prepare.py", line 288, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/Lib/site-packages/pip/_internal/req/req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/Lib/site-packages/pip/_internal/index.py", line 790, in find_requirement
    raise DistributionNotFound(
DistributionNotFound: No matching distribution found for requests
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 403 16
Status code 403 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/pip/: 403 Client Error: SNI is required for url: https://pypi.org/simple/pip/ - skipping
```

The Python Package Index (PyPI) has [discontinued support](https://github.com/pypa/pypi-support/issues/978) for Python <2.7.9 as of May 6th 2021. It now requires TLSv1.2 protocol version from pip to connect.

The built-in OpenSSL version linked with Jython 2.7.2 is too old. PyPI requires at least OpenSSL version 1.0.2 (it uses TLSv1.2 by default).

```
# jython -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.0 (as emulated by Java SSL)
```

**Comment by jeff5** [comment]
That has been raised here: https://github.com/jython/jython/issues/97.

This repo is frozen and should not be used for issues. We used to mirror the Mercurial repo on python.org infrastructure to here.

Keeping it as "last seen" feels something of safety-net, but I'll turn issues off here.
